In [730]:
import numpy as np

In [731]:
cost_function(y,y)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [938]:
class NN:
    def __init__(self, sizes, epochs, alpha = 0.001):
        self.sizes = sizes
        self.epochs = epochs
        self.alpha = alpha

        self.params = self.initial()

    def relu(self, x):
        return np.maximum(0,x)

    def relu_deriv(self, x):
        return (x > 0).astype(int)

    def sigmoid(self, x, derivative=False):
        if derivative:
            return (np.exp(-x))/((np.exp(-x)+1)**2)
        return 1/(1 + np.exp(-x))

    def cost_fun(self, output, y):
        return (output - y)**2 / output.shape[0]

    def cost_fun_deriv(self, output, y):
        return 2*(output - y) / output.shape[0]
    

    def initial(self):
        self.input = self.sizes[0]
        self.hidden_1 = self.sizes[1]
        hidden_2 = self.sizes[2]
        output = self.sizes[3]    

        params = {
            'W1':np.random.rand(self.hidden_1, self.input) * np.sqrt(1. / self.hidden_1),
            'B1':np.random.randn(self.hidden_1, 1) * np.sqrt(1. / self.hidden_1),
            'W2':np.random.rand(hidden_2, self.hidden_1) * np.sqrt(1. / hidden_2),
            'B2':np.random.randn(hidden_2, 1) * np.sqrt(1. / hidden_2),
            'W3':np.random.rand(output, hidden_2) * np.sqrt(1. / output),
            'B3':np.random.randn(output, 1) * np.sqrt(1. / output),
        }

        return params

    def forward(self, x):
        params = self.params 

        params['A0'] = x
        params['Z1'] = np.dot(params['W1'],params['A0']).reshape((self.hidden_1,self.input)) + params['B1']

        params['A1'] = self.relu(params['Z1'])
      
        params['Z2'] = np.dot(params['W2'],params['A1']) + params['B2']
        params['A2'] = self.relu(params['Z2'])

        params['Z3'] = np.dot(params['W3'],params['A2']) + params['B3']
        params['A3'] = self.relu(params['Z3'])

        return params['A3']

    def back_prop(self, y, output):
        params = self.params
        weights = {}

        temp = self.cost_fun_deriv(output, y) * self.relu_deriv(params['Z3'])
        weights['W3'] = np.outer(temp, params['A2'])
        weights['B3'] = temp

        temp = np.dot(params['W3'].T, temp) * self.relu_deriv(params['Z2'])
        weights['W2'] = np.outer(temp, params['A1'])
        weights['B2'] = temp
      
        temp = np.dot(params['W2'].T, temp) * self.relu_deriv(params['Z1'])
        weights['W1'] = np.outer(temp, params['A0'])
        weights['B1'] = temp

        return weights


    def update(self, weights):
        for key, val in weights.items():
            for w in self.params[key]:
                w -= self.alpha * val[0]
    
    def train(self, x, y):
        for iter in range(self.epochs):
            for ex, why in zip(x, y):
                output = self.forward(ex)
                change_w = self.back_prop(why, output)
                self.update(change_w)





    

In [944]:
x = np.array([[1],[2],[3]]).reshape(3,1)
y = 5*x


sizes=[1, 100, 100, 1]
ann = NN(sizes, 300, alpha = 0.001)
ann.train(x, y)

In [947]:
ann.forward(np.array([5]))

array([[25.06279726]])

In [722]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor((100,100,), max_iter=1000)

In [723]:
mlp.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MLPRegressor(hidden_layer_sizes=(100, 100), max_iter=1000)

In [725]:
mlp.score(x,y)

0.9849064380170455

In [904]:
mlp.predict(np.array([-200,300]).reshape(-1, 1))

array([   6.60513057, 1573.80885766])

array([[2, 3],
       [2, 3]])